### ISSUE TITLE
edit mode

### ISSUE THREAD

**Issue by dmitrychel** [sutara79/jquery.add-input-area#2]
Hello, @sutara79 !

Thx for add-input-area plugin! 
What would be the best way to use it in the edit mode ?

**Comment by sutara79** [comment]
Hello, @dmitrychel 

Do you mean you want a simple demo?  
I created it.
Please look at followings.

- demo: http://usamimi.info/~sutara/sample/add-input-area/demo/simple/
- source code: https://github.com/sutara79/jquery.add-input-area/tree/master/demo/simple
