### ISSUE TITLE
Renumbering for="" attributes does not work

### ISSUE THREAD

**Issue by nhuillard** [sutara79/jquery.add-input-area#7]
I had to replace the 'id' on line 218 for make for="" renumbering work. Your own sample with `<label>` do not work [/jquery.add-input-area/demo/options/](https://sutara79.github.io/jquery.add-input-area/demo/options/
)
```
 // Rename "for" attribute.
      .find('[for]').each(function() {
        $(this).attr('for', self._getValOfAttr(this, idx, 'for'));
});
```
Thanks for this very useful tool!

**Comment by sutara79** [comment]
I am sorry for the delay in my response.
I fixed this error, thogh testing on Travis CI is failed.
